CREATE DATABASE CLASSWORK
USE CLASSWORK

CREATE TABLE STUDENT(

ID INT PRIMARY KEY IDENTITY,
NAME NVARCHAR(100),
AGE INT NOT NULL
)


INSERT INTO STUDENT VALUES ('FATIME',19)
INSERT INTO STUDENT VALUES ('SIMARE',19)

SELECT * FROM STUDENT


update STUDENT
set name='IBRA'
where id=1

DELETE FROM STUDENT WHERE ID=1



CREATE TABLE [GROUP](
ID INT PRIMARY KEY IDENTITY,
[NAME] NVARCHAR (50) UNIQUE,
LIMIT INT NOT NULL
)

INSERT INTO [GROUP] VALUES('BP201',16)
INSERT INTO [GROUP] VALUES('BP202',16)
INSERT INTO [GROUP] VALUES('DB208',20)
INSERT INTO [GROUP] VALUES('BN121',18)


SELECT * FROM [GROUP]

DELETE FROM [GROUP] WHERE ID=1

update [GROUP]
set LIMIT=16
where id=5
